apiVersion: v1
kind: Secret
metadata:
  name: beeshoes-be-secret
  namespace: beeshoes
type: Opaque
stringData:
    # Database
    DB_URL: "jdbc:mariadb://beeshoes-db-service:3306/beeshoes"
    DB_USERNAME: "beeshoes"
    DB_PASSWORD: "StrongPa55WorD"
    DB_INIT_DATABASE: "beeshoes"
    # Cloudinary
    CLOUDINARY_NAME: "username"
    CLOUDINARY_API_KEY: "apikey"
    CLOUDINARY_API_SECRET: "secret"
    # Email
    MAIL_HOST: "smtp.gmail.com"
    MAIL_PORT: "587"
    MAIL_USERNAME: "beesneakerfpthn@gmail.com"
    MAIL_PASSWORD: "your-mail-password-here"
    # JWT
    JWT_SECRET: "your-jwt-secret-here"
    # Config
    CLIENT_DOMAIN: "https://beeshoes.deploy.io.vn"


