stages:
  - detect_changes
  - build
  - security_scan
  - push

variables:
  TRIVY_IMAGE: "ghcr.io/aquasecurity/trivy:latest"  # Use the official Trivy image
  BE_IMAGE: $HARBOR_URL/$PROJECT_NAME/backend:$CI_COMMIT_SHORT_SHA
  FE_IMAGE: $HARBOR_URL/$PROJECT_NAME/frontend:$CI_COMMIT_SHORT_SHA


#default:
#  before_script:
#  - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin 

detect_changed_folders:
  stage: detect_changes
  script:
    - |
      # Get the list of changed files in Application-Code directory
      CHANGED_FILES=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA -- Application-Code/)
      
      # Extract the top-level directories that changed
      CHANGED_DIRS=$(echo "$CHANGED_FILES" | grep "^Application-Code/" | awk -F/ '{print $2}' | sort -u )
      
      # Output the changed folders
      echo "Changed folders in Application-Code:"
      if [ -z "$CHANGED_DIRS" ]; then
        echo "No changes detected in Application-Code directory"
      else
        echo "$CHANGED_DIRS"
        # Save to a file for use in later stages
      fi
    - echo "$CHANGED_DIRS" > changed_dirs.env
  artifacts:
    paths:
      - changed_dirs.env

build-containers:
  stage: build
  script:
    - cat changed_dirs.env
    - CHANGED_DIRS=$(cat changed_dirs.env)
    - for DIR in $CHANGED_DIRS; do docker build -t $HARBOR_URL/$PROJECT_NAME/$DIR:$CI_COMMIT_SHORT_SHA ./Application-Code/$DIR; done

trivy-code-scan:
  stage: security_scan
  services:
    - docker:dind
  script:
    - mkdir code-scan-results
    - CHANGED_DIRS=$(cat changed_dirs.env)
    - for DIR in $CHANGED_DIRS; do docker run --rm -v $(pwd):/app $TRIVY_IMAGE fs --severity HIGH,CRITICAL --no-progress --ignore-unfixed /app/Application-Code/$DIR >> code-scan-results/$DIR-scan-results.txt; done
  artifacts:
    paths:
      - code-scan-results/*-scan-results.txt     

trivy-image-scan:
  stage: security_scan
  services:
    - docker:dind
  script:
    - mkdir image-scan-results
    - IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep ":${CI_COMMIT_SHORT_SHA}$")
    - for IMAGE in $IMAGES; do docker run --rm $TRIVY_IMAGE image --severity HIGH,CRITICAL --no-progress --ignore-unfixed $IMAGE >> image-scan-results/${IMAGE//[\/:]/_}-scan-results.txt; done
  artifacts:
    paths:
      - image-scan-result/*-scan-results.txt      
    # Filesystem scan (code scan)
    #- trivy fs --exit-code 0 --severity HIGH,CRITICAL --no-progress ./Application-Code
    
    # Container image scan
    #- trivy image --exit-code 1 --severity HIGH,CRITICAL --no-progress $DOCKER_IMAGE

push-container:
  stage: push
  services:
    - docker:dind
  script:
    - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin 
    - IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep ":${CI_COMMIT_SHORT_SHA}$")
    - for IMAGE in $IMAGES; do docker push $IMAGE; done
  when: manual


