stages:
  - detect_changes
  - build
  - scan
  - approve
  - push

variables:
  TRIVY_IMAGE: "ghcr.io/aquasecurity/trivy:latest"  # Use the official Trivy image
  ARTIFACT_DIR: "trivy-results"  # Directory to store scan results
  BE_IMAGE: $HARBOR_URL/$PROJECT_NAME/backend:$CI_COMMIT_SHORT_SHA
  FE_IMAGE: $HARBOR_URL/$PROJECT_NAME/frontend:$CI_COMMIT_SHORT_SHA


#default:
#  before_script:
#  - echo "$HARBOR_PASSWD" | docker login $HARBOR_URL -u 'robot$'"$HARBOR_USERNAME" --password-stdin 

detect_changed_folders:
  stage: detect_changes
  script:
    - |
      if [ -n "$CI_MERGE_REQUEST_IID" ]; then
        # In merge request context
        git diff --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA $CI_COMMIT_SHA > changed_files.txt
      else
        # In branch context
        git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA > changed_files.txt
      fi
    - cat changed_files.txt | xargs -I{} dirname {} | sort -u > changed_folders.txt
    - echo "Changed folders:"
    - cat changed_folders.txt

build-backend:
  stage: build
  script:
    - docker build -t $BE_IMAGE ./Application-Code/backend

build-frontend:
  stage: build
  script:
    - docker build -t $FE_IMAGE ./Application-Code/frontend

trivy-image-scan:
  stage: scan
  services:
    - docker:dind
  script:
    - mkdir -p $ARTIFACT_DIR
    - IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep ":${CI_COMMIT_SHORT_SHA}$")
    - for IMAGE in $IMAGES; do docker run --rm -v /var/run/docker.sock:/var/run/docker.sock $TRIVY_IMAGE image --severity HIGH,CRITICAL --ignore-unfixed $IMAGE >> $ARTIFACT_DIR/${IMAGE//[\/:]/_}-scan-results.txt; done
  artifacts:
    paths:
      - $ARTIFACT_DIR/*-scan-results.txt      
    # Filesystem scan (code scan)
    #- trivy fs --exit-code 0 --severity HIGH,CRITICAL --no-progress ./Application-Code
    
    # Container image scan
    #- trivy image --exit-code 1 --severity HIGH,CRITICAL --no-progress $DOCKER_IMAGE

review_findings:
  stage: approve
  script:
    - echo "Review scan results and artifacts before pushing to registry"
  when: manual
  allow_failure: false

