apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beeshoes-db-pvc
  namespace: beeshoes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage-retain
  resources:
    requests:
      storage: 5Gi
