apiVersion: v1
kind: Secret
metadata:
  name: beeshoes-db-secret
  namespace: beeshoes
type: Opaque
stringData:
  DB_ROOT_PASSWORD: StrongPa55WorD
  DB_PASSWORD: StrongPa55WorD
  DB_USERNAME: beeshoes
  DB_INIT_DATABASE: beeshoes
  DB_HOST: beeshoes-db-service

