apiVersion: v1
kind: Service
metadata:
  name: beeshoes-db-service
  namespace: beeshoes
spec:
  selector:
    app: beeshoes-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
