apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      imagePullSecrets:
          - name: harbor-secret
      containers:
      - name: frontend
        image: redacted/three_tier_app/frontend:8b629682
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "https://redacted/api/tasks"
        ports:
        - containerPort: 3000
